### ISSUE TITLE
hi sorry for bugging you 

### ISSUE THREAD

**Issue by Master3636363636** [Puyodead1/Run8-V3-reverse-engineering#2]
you said that Writing defectdetectorlist back to r8 has been added in [cf61ef2](https://github.com/Puyodead1/Run8-V3-reverse-engineering/commit/cf61ef248c58ef8ff6fa4aac85bf972b3056ffcf) but i dont see it. where would the defectdetectorlist.cs back to the R8.file be cause i dont know anything about doing this lol i just know how to mod horns and paint schemes for run 8

**Comment by Puyodead1** [comment]
> you said that Writing defectdetectorlist back to r8 has been added in [cf61ef2](https://github.com/Puyodead1/Run8-V3-reverse-engineering/commit/cf61ef248c58ef8ff6fa4aac85bf972b3056ffcf) but i dont see it. where would the defectdetectorlist.cs back to the R8.file be cause i dont know anything about doing this lol i just know how to mod horns and paint schemes for run 8

https://github.com/Puyodead1/Run8-V3-reverse-engineering/blob/refactor/Run8/Test/Program.cs#L51-L57 <- this is the test program, the same place you would convert the r8 to json
https://github.com/Puyodead1/Run8-V3-reverse-engineering/blob/refactor/Run8/LibRun8/Formats/DefectDetectorList.cs#L27-L63

**Comment by Master3636363636** [comment]
> > you said that Writing defectdetectorlist back to r8 has been added in [cf61ef2](https://github.com/Puyodead1/Run8-V3-reverse-engineering/commit/cf61ef248c58ef8ff6fa4aac85bf972b3056ffcf) but i dont see it. where would the defectdetectorlist.cs back to the R8.file be cause i dont know anything about doing this lol i just know how to mod horns and paint schemes for run 8
> 
> https://github.com/Puyodead1/Run8-V3-reverse-engineering/blob/refactor/Run8/Test/Program.cs#L51-L57 <- this is the test program, the same place you would convert the r8 to json https://github.com/Puyodead1/Run8-V3-reverse-engineering/blob/refactor/Run8/LibRun8/Formats/DefectDetectorList.cs#L27-L63

would i place the Program.cs anywhere or would i have to open the defectdetectorlist.cs file with the program.cs file or is it a different method?
